Update: #docker: Add docker file
AeroWang/XanaduCompany pull request #17
Opened 2023-08-10 10:51 UTC by RinpoStk

增加了linux下的dockerfile
修改一处命名问题

2023-08-12 03:44 UTC, AeroWang commented
简单看了下，确实是简化了数据库的初始化流程，但是没有整体部署出来。

可不可以使用 docker-compose.yaml 更简单化部署操作呢，当然，这个要记得考虑处理环境变量，还有 nginx 的相关配置。

👍

2023-08-15 13:32 UTC, RinpoStk commented
已添加 docker compose 😘

2023-08-16 15:14 UTC, AeroWang commented
LGTM

2023-08-16 15:41 UTC, AeroWang requested changes

2023-08-16 15:41 UTC, AeroWang commented on compose.yml
> +    image: xanadu-server
```suggestion
```
已经有了
```
    build:
      context: ./server
```

2023-08-16 15:41 UTC, AeroWang commented on compose.yml
> +    image: xanadu-frontend
```suggestion
```
已经有了
```
    build:
      context: .
```

2023-08-17 01:23 UTC, RinpoStk commented
已修改 @AeroWang

2023-08-17 06:36 UTC, AeroWang commented
lgtm

2023-08-17 06:37 UTC, merged